### ISSUE TITLE
Blender 2.80

### ISSUE THREAD

**Issue by Cyrus-Harding** [funjack/funscripting#7]
Are there any plans on updating the plugin for Blender 2.80?

It says "upgrade to 2.8x required"
![image](https://user-images.githubusercontent.com/10121762/61236705-f744d000-a738-11e9-8abe-e88ceeb7da3b.png)

**Comment by funjack** [comment]
I'll have to look into it, hopefully the changes aren't too drastic.

**Comment by Cyrus-Harding** [comment]
They don't look too drastic, mostly how you register classes.

**Comment by funjack** [comment]
@kimamb [here is a pre-release](https://github.com/funjack/funscripting/releases/tag/v1.0.0-alpha1) that should support Blender 2.80.

I've not tested everything, so please let me know if you run into any issues.

**Comment by Cyrus-Harding** [comment]
I can't seem to find the modifier, have you moved it?

**Comment by Cyrus-Harding** [comment]
Never mind, it's now under "Misc".
