### ISSUE TITLE
Live funscript test, feature request

### ISSUE THREAD

**Issue by ghost** [funjack/funscripting#8]
Hello Funjack
I just wanted to ask, if there is a possibility to directly connect the fleshlight launch device to the blender addon? So that you can see the movements live / in real time.
Greetings Clasher

**Comment by funjack** [comment]
In theory this should be doable, but it's not easy. The timings of the playback in Blender is a bit finicky, and I'm not sure if there are great scripting hooks. As for controlling the Launch, it would probably have to use https://buttplug.io/ and it's Python client code.

But this little project is already way bigger then I originally intended. So I don't think I will try to implement this any time soon. But if someone is willing to put in the work, I wont say no to including it.
